version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  target-branch: releases/next
  open-pull-requests-limit: 10
  allow:
    - dependency-name: "ppy.osu.*"
